### ISSUE TITLE
robots.cfg can't flag a robot that looks legit

### ISSUE THREAD

**Issue by justino** [interchange/interchange#85] opened 2013-11-21 15:59 UTC
The "NotRobotUA" directive includes the patterns "MSIE" and "Gecko" which would normally allow UAs that look legit through.

However, a recent bot has been discovered that looks like a legit Chrome install, except it has an extension in the UA. This bot, based on current robot rules, cannot be flagged as a robot because "NotRobotUA" will let it through.

Here is the UA that should be flagged:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36 Squider/0.01

The extension being "Squider/0.01"

We need someway of overriding the "NotRobotUA" so that we can block specific UAs.

**Comment by jdigory** [comment] 2016-05-17 21:06
dupe of #9

**Closed by jdigory** 2016-05-17 21:06 UTC
Labels: resolution: duplicate
