### ISSUE TITLE
RT Ticket #123: Administration/Preferences operates on variable database only

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#56] opened 2013-03-19 19:23 UTC
Created: Thu Sep 27 16:35:38 2007
Owner: Gert van der Spoel
Requestors: Stefan Hornburg

---

VariableDatabase allows you to define multiple Interchange databases to
fill the variable namespace. This is quite handy if you want to make
site specific customizations and share variable.txt across production
and development systems. Unfortunately, the UI
Administration/Preferences displays only the value variable.txt, even if
its overriden by another database like site.txt.

Regards
Racke

**Comment by jonjensen** [comment] 2020-05-09 01:17
It would probably be nice to work this out somehow, but it's not a bug or real problem, and would be big project that has never had a backer to get it done. Closing.

**Closed by jonjensen** 2020-05-09 01:17 UTC
Labels: type: feature request
